name: Check Item Status
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
      - '**.vue'
      - '**.ts'
      - .github/workflows/build.yml
      - .github/workflows/check_issue_status.yml
concurrency:
  group: "vue-${{ github.ref }}-${{ github.workspace }}"
  cancel-in-progress: true

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Check the item status
            id: check
            uses: grantmcdade/andagon-aqua-status-check@5b102a4c695bad4c5eb4b5fd1407b8d4e3eab9b6
            with:
              branch_name: '${{ github.head_ref }}'
              branch_name_expr: '(.*)\/.*'
              username: '${{ secrets.AQUA_USERNAME }}'
              password: '${{ secrets.AQUA_PASSWORD }}'
              aqua_url: '${{ secrets.AQUA_URL }}'
              status_id_to_check: '20294'
              status_not_set_message: The item is not ready to merge
              