name: Check Item Status
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
      - '**.vue'
      - '**.ts'
      - .github/workflows/build.yml
      - .github/workflows/check_issue_status.yml
concurrency:
  group: 'vue-${{ github.ref }}-${{ github.workspace }}'
  cancel-in-progress: true

jobs:
  check-if-ready-to-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check the item status
        uses: grantmcdade/andagon-aqua-status-check@v1
        with:
          branch_name: '${{ github.head_ref }}'
          branch_name_expr: '(.*)\/.*'
          username: 'McdadeGr@aquacloud'
          password: '${{ secrets.AQUA_PASSWORD }}'
          aqua_url: 'https://aqua-saas2.andagon.com/aquaWebNG'
          status_id_to_check: '20294'
          status_not_set_message: The item is not ready to merge
